### ISSUE TITLE
Isn't this two project ?

### ISSUE THREAD

**Issue by pums974** [midarrlabs/midarr-server#10]
Thanks for this project, but, I don't think we need another Plex/Jellyfin/Emby.

**But** I think it might be relevant to split this into two projects.

1. the media manager with the database and static part of the social experience (ratings for example)
2. the transcoder server with a web player and the dynamic part of the social experience (online and currently watching for example)

The media manager would:

* manage posters, metadata, collections, ...
* store the static part of the social experience: watched status / custom ratings ... (synced with trakt/imdb/...)
* **maybe** manage media requests (like [ombi](https://github.com/tidusjar/Ombi) or [overserr](https://github.com/sct/overseerr))
* **maybe** display the posters (like [posterr](https://github.com/petersem/poster))

It could be linked to Plex/Jellyfin/Emby/kodi while being independent of them (in order to use them only as player and/or transcoder server)

This would be more in the KISS design principle, and allows one to

* switch more easily from one player/platform to another
* have the database on one server and the player on another
* simplify the design of each app

(this issue has first been raised on a [reddit thread](https://www.reddit.com/r/HomeServer/comments/sj9xu1/comment/hveb29q/?utm_source=share&utm_medium=web2x&context=3))

(edit: added links)

**Comment by midarrlabs** [comment]
Hi, thank you for taking time to look into the project.

After carefully reading through your query, you raise some interesting points and concerns.
We will definitely keep your ideas in mind going forward, and will reach out in the future should we require.

Please continue to post any future ideas you may have too, we will gladly receive them.

Thanks again 😄
