### ISSUE TITLE
Scope MKV support

### ISSUE THREAD

**Issue by trueChazza** [midarrlabs/midarr-server#139]
Scope MKV support

**Comment by trueChazza** [comment]
After some initial testing... it does play mkv (codec H.264, audio AAC, Chrome Browser)

**Comment by trueChazza** [comment]
Will do some further tests before closing this issue off.

**Comment by Erwyn** [comment]
On Linux, tested with Chromium and Firefox

I can confirm the following:

* MKV works for Chromium
* MKV does not work for Firefox

**Comment by trueChazza** [comment]
Awesome, thanks for testing this out and reporting back.

I'll close this issue off with an update to the README. Thanks!
