### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tavalin** [midarrlabs/midarr-server#14]
Hi

I've tried to setup the midarr server using the `docker-compose` example in the `README` to connect to my existing radarr and sonarr servers. The midarr server starts correctly and I'm able to log in and view the settings page but once adding the radarr details or the sonarr details the homepage returns `Internal Server Error`.

Here's the log from the server:

```
[debug] QUERY OK source="users_tokens" db=0.5ms idle=53.5ms

SELECT u1."id", u1."email", u1."name", u1."hashed_password", u1."confirmed_at", u1."is_admin", u1."inserted_at", u1."updated_at" FROM "users_tokens" AS u0 INNER JOIN "users" AS u1 ON u1."id" = u0."user_id" WHERE ((u0."token" = $1) AND (u0."context" = $2)) AND (u0."inserted_at" > $3::timestamp + (-(60)::numeric * interval '1 day')) [<<31, 180, 28, 124, 201, 138, 240, 59, 237, 45, 158, 41, 194, 43, 79, 181, 1, 50, 8, 180, 18, 206, 57, 116, 140, 87, 217, 119, 11, 186, 130, 27>>, "session", ~U[2022-02-08 16:47:20.084905Z]]

[debug] QUERY OK source="radarrs" db=0.1ms idle=54.4ms

SELECT r0."id", r0."api_key", r0."name", r0."url", r0."inserted_at", r0."updated_at" FROM "radarrs" AS r0 ORDER BY r0."inserted_at" DESC LIMIT 1 []

[debug] QUERY OK source="radarrs" db=0.2ms idle=54.7ms

SELECT r0."id", r0."api_key", r0."name", r0."url", r0."inserted_at", r0."updated_at" FROM "radarrs" AS r0 ORDER BY r0."inserted_at" DESC LIMIT 1 []

[debug] QUERY OK source="sonarrs" db=0.1ms idle=54.9ms

SELECT s0."id", s0."api_key", s0."name", s0."url", s0."inserted_at", s0."updated_at" FROM "sonarrs" AS s0 ORDER BY s0."inserted_at" DESC LIMIT 1 []

[debug] QUERY OK source="sonarrs" db=0.5ms idle=55.2ms

SELECT s0."id", s0."api_key", s0."name", s0."url", s0."inserted_at", s0."updated_at" FROM "sonarrs" AS s0 ORDER BY s0."inserted_at" DESC LIMIT 1 []

[info] Sent 500 in 5ms

[debug] Converted error Jason.DecodeError to 500 response

[error] #PID<0.720.0> running MediaServerWeb.Endpoint (connection #PID<0.718.0>, stream id 1) terminated

Server: 192.168.0.200:4010 (http)

Request: GET /

** (exit) an exception was raised:

    ** (Jason.DecodeError) unexpected byte at position 0: 0x3C ("<")

        (jason 1.3.0) lib/jason.ex:92: Jason.decode!/2

        (media_server 0.1.0) lib/media_server_web/repositories/series.ex:31: MediaServerWeb.Repositories.Series.get_latest/1

        (media_server 0.1.0) lib/media_server_web/live/home_live/index.ex:27: MediaServerWeb.HomeLive.Index.apply_action/3

        (media_server 0.1.0) lib/media_server_web/live/home_live/index.ex:6: MediaServerWeb.HomeLive.Index.handle_params/3

        (phoenix_live_view 0.17.6) lib/phoenix_live_view/utils.ex:369: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5

        (telemetry 1.0.0) /app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3

        (phoenix_live_view 0.17.6) lib/phoenix_live_view/static.ex:271: Phoenix.LiveView.Static.call_mount_and_handle_params!/5

        (phoenix_live_view 0.17.6) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3

        (phoenix_live_view 0.17.6) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3

        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2

        (media_server 0.1.0) lib/media_server_web/endpoint.ex:1: MediaServerWeb.Endpoint.plug_builder_call/2

        (media_server 0.1.0) lib/media_server_web/endpoint.ex:1: MediaServerWeb.Endpoint.call/2

        (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4

        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2

        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3

        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3

        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by trueChazza** [comment]
Hi, thanks for opening issue.

Interesting. What version of Radarr and Sonarr do you run?

**Comment by tavalin** [comment]
Currently:
Radarr - 4.0.5.5923
Sonarr - 3.0.6.1457

**Comment by musgos** [comment]
Hi 
Same problem here.

Sonarr:

Version
    3.0.6.1342
Package Version
    3.0.6.1342-ls133 by [linuxserver.io](https://linuxserver.io/)

Radarr:

Version
    4.0.4.5922
Package Version
    4.0.4.5922-ls130 by linuxserver.io 

Midarr log:

[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser, :require_authenticated_user]
[debug] QUERY OK source="users_tokens" db=4.1ms idle=1784.6ms
SELECT u1."id", u1."email", u1."name", u1."hashed_password", u1."confirmed_at", u1."is_admin", u1."inserted_at", u1."updated_at" FROM "users_tokens" AS u0 INNER JOIN "users" AS u1 ON u1."id" = u0."user_id" WHERE ((u0."token" = $1) AND (u0."context" = $2)) AND (u0."inserted_at" > $3::timestamp + (-(60)::numeric * interval '1 day')) [<<209, 95, 146, 114, 167, 254, 141, 26, 149, 98, 125, 96, 219, 108, 146, 71, 184, 246, 197, 27, 211, 176, 2, 175, 21, 101, 14, 103, 26, 197, 169, 143>>, "session", ~U[2022-02-09 18:37:29.969595Z]]
[debug] QUERY OK source="radarrs" db=1.7ms idle=1789.1ms
SELECT r0."id", r0."api_key", r0."name", r0."url", r0."inserted_at", r0."updated_at" FROM "radarrs" AS r0 ORDER BY r0."inserted_at" DESC LIMIT 1 []
[debug] QUERY OK source="radarrs" db=0.6ms idle=790.9ms
SELECT r0."id", r0."api_key", r0."name", r0."url", r0."inserted_at", r0."updated_at" FROM "radarrs" AS r0 ORDER BY r0."inserted_at" DESC LIMIT 1 []
[debug] QUERY OK source="sonarrs" db=1.0ms idle=791.7ms
SELECT s0."id", s0."api_key", s0."name", s0."url", s0."inserted_at", s0."updated_at" FROM "sonarrs" AS s0 ORDER BY s0."inserted_at" DESC LIMIT 1 []
[debug] QUERY OK source="sonarrs" db=0.7ms idle=792.9ms
SELECT s0."id", s0."api_key", s0."name", s0."url", s0."inserted_at", s0."updated_at" FROM "sonarrs" AS s0 ORDER BY s0."inserted_at" DESC LIMIT 1 []
[info] Sent 500 in 16ms
[debug] Converted error Jason.DecodeError to 500 response
[error] #PID<0.734.0> running MediaServerWeb.Endpoint (connection #PID<0.733.0>, stream id 1) terminated
Server: 192.168.10.13:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Jason.DecodeError) unexpected byte at position 0: 0x3C ("<")
        (jason 1.3.0) lib/jason.ex:92: Jason.decode!/2
        (media_server 0.1.0) lib/media_server_web/repositories/series.ex:31: MediaServerWeb.Repositories.Series.get_latest/1
        (media_server 0.1.0) lib/media_server_web/live/home_live/index.ex:27: MediaServerWeb.HomeLive.Index.apply_action/3
        (media_server 0.1.0) lib/media_server_web/live/home_live/index.ex:6: MediaServerWeb.HomeLive.Index.handle_params/3
        (phoenix_live_view 0.17.6) lib/phoenix_live_view/utils.ex:369: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
        (telemetry 1.0.0) /app/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
        (phoenix_live_view 0.17.6) lib/phoenix_live_view/static.ex:271: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.17.6) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.17.6) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (media_server 0.1.0) lib/media_server_web/endpoint.ex:1: MediaServerWeb.Endpoint.plug_builder_call/2
        (media_server 0.1.0) lib/media_server_web/endpoint.ex:1: MediaServerWeb.Endpoint.call/2
        (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by trueChazza** [comment]
Thank you for the detailed info. I will attempt to replicate the error, and let you know how I get on.

**Comment by trueChazza** [comment]
I was unable to replicate this.

The error is due to a non json response being passed into the decoder. Please check your integration settings, and ensure `Midarr` is able to resolve your integration URLs.

**Comment by trueChazza** [comment]
```bash
docker compose exec web curl sonarr:8989/api/v3
```

If you're running the docker compose example, it should return this from the command line (replace with your URL):

```bash
{
  "error": "Unauthorized"
}% 
```
