### ISSUE TITLE
Scope adding Chromecast button

### ISSUE THREAD

**Issue by trueChazza** [midarrlabs/midarr-server#141]
Scope adding Chromecast button to the app interface.

**Comment by trueChazza** [comment]
Closing for now as casting from a web browser is available through the native interface.

**Comment by Erwyn** [comment]
Hi @trueChazza, just as a note about this feature, I'm not sure using the native interface leads to the expected behaviour. In my previous tests, on Desktop on Chrome I can of course use the Cast option from the browser. But If I do so, It's casting my tab by default instead of reading the dedicated stream coming from the server and I don't know how to tell it to use the stream instead. Do note that it's not the case from a mobile phone, casting seems to end up with "real casting".

**Comment by trueChazza** [comment]
#150

Hi @Erwyn I've opted to move this into a discussion for further scope and feedback.

I feel this does not quite warrant an issue just yet, as it is rather open ended. This way I can keep the scope tight and open specific issues to address this feature along the way.

Thanks for your feedback 😄

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/releases/tag/v1.16.0-beta.4

Hi @Erwyn would you be interested in testing this release out? I've added the Chromecast SDK which provides the communication link between the sender and Chromecast - as opposed to just casting the browser tab. It is just the first pass at this integration.

I'd be interested to hear your initial feedback on this 😄

https://github.com/midarrlabs/midarr-server/pull/158#discussion_r955994106
*Please note `APP_URL` environment variable will need to be set with https.

Thanks!

**Comment by trueChazza** [comment]
@Erwyn There's currently a bug in the build. I'll let you know when you can test it out, thanks.

**Comment by Erwyn** [comment]
Sure, just ping me when it's ready (I've seen your build issue) 

Le 27 août 2022 04:20:02 GMT+02:00, Chaz Goodare ***@***.***> a écrit :

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/pkgs/container/midarr-server/39501451?tag=v1.16.0-beta.16

Hi @Erwyn this release is now ready, thanks.

**Comment by Erwyn** [comment]
Hi @trueChazza

I'm not sure where to find the button. Do you have a screen capture of where it should appear ?

**Comment by trueChazza** [comment]
Sorry about that I didn’t explain this.

No there is no button, if you cast from the browser button it should now cast using the stream and not just cast the tab.

**Comment by trueChazza** [comment]
Cast when the video is playing.

**Comment by Erwyn** [comment]
It works on my side

**Comment by trueChazza** [comment]
Awesome thank you for reporting back.
