### ISSUE TITLE
Restore SQLite support

### ISSUE THREAD

**Issue by subvillion** [midarrlabs/midarr-server#143]
`Midarr is a minimal lightweight media server for enjoying your media` actually no, because "full feathured jellyfin", plex or emby - have no hard postgress dependency, but midarr - have it. 

Please [back](https://github.com/midarrlabs/midarr-server/commit/c8c017ea45d69e875042fa4294c05f17745fef2d) support SQLite as option. 

tnx

**Comment by trueChazza** [comment]
Hi there, thank you for opening this issue.

After consideration - adding SQLite support back in would at this stage be a breaking change.
I've created a scope issue to further investigate this option, and tagged it to the next version (v2.0.0) milestone.

Feel free to subscribe to the scope ticket for future updates.

Thank you!

**Comment by trueChazza** [comment]
#148

I've decided to move this into Discussions instead. This allows us a space to first think through (and discuss) why this should be considered being added back in.

Feel free to add your input and feedback there, thank you!

**Comment by trueChazza** [comment]
Hi @subvillion, I'm happy to announce SQLite is currently in beta. Expect a release soon, thanks!

**Comment by trueChazza** [comment]
Hi @subvillion, v2 has been released with full SQLite support. Feel free to check it out and let me know if you run into any issues.
