### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by akashkj** [midarrlabs/midarr-server#15]
Using multi arch image

Getting invalid login error

Logs from the app for login, which looks ok to me
```
[info] POST /login
[debug] Processing with MediaServerWeb.UserSessionController.create/2
  Parameters: %{"_csrf_token" => "MSw3aBc5WxMJMRFBZlg5FCY5XhkIYSEDgGbPHJlADud703XsnRkKgSh0", "user" => %{"email" => "<masked>", "password" => "[FILTERED]", "remember_me" => "true"}}
  Pipelines: [:browser, :redirect_if_user_is_authenticated]
[debug] QUERY OK source="users" db=1.3ms idle=831.3ms
SELECT u0."id", u0."email", u0."name", u0."hashed_password", u0."confirmed_at", u0."is_admin", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."email" = $1) ["<masked>"]
[info] Sent 200 in 260ms
```

![image](https://user-images.githubusercontent.com/14318173/153108443-587682fe-c22c-4549-9cf0-bafd4ea6f00b.png)

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/blob/master/README.md?plain=1#L55-L89

Did you use the documented steps?

<img width="1438" alt="Screen Shot 2022-02-09 at 3 30 39 PM" src="https://user-images.githubusercontent.com/20368025/153110695-2ca7eb3f-2784-4a22-89d7-28c4e4dba3f8.png">

I've just tested and all is working.
Password must be min `12` and max `72` length.

**Comment by trueChazza** [comment]
I suspect validation fails silently when creating a user. I'll update the readme for now.

**Comment by trueChazza** [comment]
Also feel free to use the `latest` tagged image, as it now has multi arch support.

**Comment by akashkj** [comment]
It worked, thanks.
