### ISSUE TITLE
DB user, password, database name can't be configured as environment variable

### ISSUE THREAD

**Issue by edasque** [midarrlabs/midarr-server#2]
While the db host can (DB_HOSTNAME). It would be great to be able to do so for the others.

(Also, do you have instructions on what table to insert admin Midair user info in? SQL code would be nice)

**Comment by Arcanemagus** [comment]
Once you have the stack up you have to run `mix ecto.migrate` in a shell on the Midarr container to actually create the database tables. Why this doesn't happen automatically, or at least get documented anywhere as a required step is beyond me...

**Comment by edasque** [comment]
Good to know, thank you. Doable by exec bash into docker but painful.

I need to be able to configure user, password & db name as ENV variables unless I am ok with standard one for now

**Comment by trueChazza** [comment]
> Once you have the stack up you have to run `mix ecto.migrate` in a shell on the Midarr container to actually create the database tables. Why this doesn't happen automatically, or at least get documented anywhere as a required step is beyond me...

> Good to know, thank you. Doable by exec bash into docker but painful.
I need to be able to configure user, password & db name as ENV variables unless I am ok with standard one for now. I imagine port would be nice too.

Sorry about that. In an effort to include everything in the readme, I've missed critical parts for actually running it.

https://github.com/midarrlabs/midarr-server/issues/3
https://github.com/midarrlabs/midarr-server/issues/4
https://github.com/midarrlabs/midarr-server/issues/5

I've created a few issues to address this. Thank you for reporting 👍

**Comment by edasque** [comment]
@trueChazza I don't see anything in these new issues regarding being able to set these parameters from the config via ENV variable, however.

Like you do here: ```  hostname: System.get_env("DB_HOSTNAME") || "postgresql",```

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/issues/5

The production build issue provides a brief description.

**Comment by trueChazza** [comment]
Resolved in version 0.35.0
