### ISSUE TITLE
Possible to use with rclone?

### ISSUE THREAD

**Issue by heryoff** [midarrlabs/midarr-server#208]
Hello 👋 , 
I was searching around for a open source lightweight media server and came across yours, It looks super pretty but I was wondering it it's possible to make it use rclone mount as a media folder? Without the radarr and sonarr integration

**Comment by trueChazza** [comment]
Hi!
Thank you for your query. Midarr depends on Radarr / Sonarr integrations for an index to your media, there is currently no plans yet for Midarr to handle this exclusively.

As a stopgap in the meantime, could you mount your rclone to a Radarr / Sonarr instance instead?

**Comment by heryoff** [comment]
Yeah sure, I'm trying to with docker-compose but I keep getting this error:
```Step 3/19 : COPY assets/package.json assets/package-lock.json /assets
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR: Service 'midarr' failed to build : Build failed```

Using the default docker-compose from your repository. Ubuntu server on arm

**Comment by trueChazza** [comment]
Thanks for reporting back. I have tagged a new version which should fix the error you were seeing.

Please use the new tag `v1.16.1` or rebuild `latest`

```
ghcr.io/midarrlabs/midarr-server:v1.16.1
```

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server#volumes

Remember also to mount your rclone into both Radarr / Sonarr and Midarr for your media location to resolve.
