### ISSUE TITLE
Internal server error : (File.Error) could not list directory

### ISSUE THREAD

**Issue by parer55** [midarrlabs/midarr-server#251]
Hello everyone,
Trying Midarr today on Ubuntu 22.04 and using docker-compose via Portainer.
Weird thing, when I want to play a movie, it says "Internal server error" and in the logs I have this.
Weird because it can list movies and TV shows, but not read them.

> 12:33:16.162 [info]  Migrations already up
** (Ecto.ConstraintError) constraint error when attempting to insert struct:
    * media_types_type_index (unique_constraint)
If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.
The changeset has not defined any constraint.
    (ecto 3.9.3) lib/ecto/repo/schema.ex:795: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.9.3) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.9.3) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.9.3) lib/ecto/repo/schema.ex:369: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    priv/repo/seeds.exs:15: (file)
12:33:28.130 [info] Running MediaServerWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
12:33:28.139 [info] Access MediaServerWeb.Endpoint at http://localhost:4000
12:33:31.421 request_id=FzneWT4cf4t3344AAAGh [info] GET /settings
12:33:31.543 request_id=FzneWT4cf4t3344AAAGh [info] Sent 200 in 121ms
12:33:31.637 [info] CONNECTED TO MediaServerWeb.UserSocket in 55µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
12:33:31.662 [info] CONNECTED TO Phoenix.LiveView.Socket in 28µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "Z2YoZ0sjGkZjTUR6MjExIAUTAhEXCDATV9lR3LVkRy61QwTm1DiR_rgz", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://192.168.1.15:5069/assets/app-32f76cceaa1ca28a4e35a4a97246edde.css?vsn=d", "1" => "http://192.168.1.15:5069/assets/app-9c59922c8076f5a7842385ca1d3f8000.js?vsn=d"}, "vsn" => "2.0.0"}
12:33:31.707 [info] JOINED room:lobby in 26µs
  Parameters: %{"current_location" => "http://192.168.1.15:5069/settings", "page_title" => "Settings", "user_id" => 1, "user_name" => "MYUSERNAME"}
12:33:34.974 request_id=FzneWhH2ErRu3m0AAAKh [info] GET /movies/574/watch
12:33:35.017 request_id=FzneWhH2ErRu3m0AAAKh [info] Sent 500 in 43ms
12:33:35.021 [error] #PID<0.596.0> running MediaServerWeb.Endpoint (connection #PID<0.579.0>, stream id 5) terminated
Server: 192.168.1.15:5069 (http)
Request: GET /movies/574/watch
** (exit) an exception was raised:
    ** (File.Error) could not list directory "/path/to/my/movies/Everything Everywhere All at Once (2022)": no such file or directory
        (elixir 1.13.4) lib/file.ex:1590: File.ls!/1
        (media_server 2.0.0) lib/media_server/subtitles.ex:15: MediaServer.Subtitles.get_subtitle/2
        (media_server 2.0.0) lib/media_server/subtitles.ex:22: MediaServer.Subtitles.has_subtitle/2
        (media_server 2.0.0) lib/media_server_web/live/watch_movie_live/show.html.heex:18: anonymous fn/2 in MediaServerWeb.WatchMovieLive.Show.render/1
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
12:33:36.506 request_id=FzneWm0_dYgGm5UAAALh [info] GET /
12:33:36.533 request_id=FzneWm0_dYgGm5UAAALh [info] Sent 200 in 27ms
12:33:36.655 [info] CONNECTED TO MediaServerWeb.UserSocket in 119µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
12:33:36.690 [info] CONNECTED TO Phoenix.LiveView.Socket in 96µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "fxAFTRwZDm5JBzkfEh9WDnseHhonKS4dNOAxdvBCx3KTqY3COIuYoSyt", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://192.168.1.15:5069/assets/app-32f76cceaa1ca28a4e35a4a97246edde.css?vsn=d", "1" => "http://192.168.1.15:5069/assets/app-9c59922c8076f5a7842385ca1d3f8000.js?vsn=d"}, "vsn" => "2.0.0"}
12:33:36.693 [info] JOINED room:lobby in 53µs
  Parameters: %{"current_location" => "http://192.168.1.15:5069/", "page_title" => "Home", "user_id" => 1, "user_name" => "MYUSERNAME"}

**Comment by parer55** [comment]
And thank you for your time.

**Comment by lukebrandt** [comment]
I am running into this error as well.  Just set up Midarr on my Synology 920+ using docker-compose.  Tried it with the midarr user having read, and then tried it with read/write.

My paths match with Sonarr and Radarr on the left-hand side in docker-compose.

**Comment by parer55** [comment]
Precision : data is on an external drive. But it isn't a problem on my other docker images running. Like sonarr for instance.

**Comment by trueChazza** [comment]
Hi, thanks for opening the issue and detailed info.

Based on your logs it could be subtitle related. I’ll look into this further.

Does playback of other movies work?

**Comment by parer55** [comment]
Thanks for the reply. Unfortunately, no, no movie or TV show is working. None. Thanks for the check up. If you need anything just ask, I'll gladly answer as far as my knowledge goes.

**Comment by parer55** [comment]
OK, I tried deleting every subtitles on the movie folder then redeploying the docker image. Same result and same logs. Weird!

**Comment by trueChazza** [comment]
Interesting, let me look into this further and I’ll get back to you.

**Comment by trueChazza** [comment]
#### Movies
Midarr - https://github.com/midarrlabs/midarr-server/blob/master/docker-compose.yml#L10
Radarr - https://github.com/midarrlabs/midarr-server/blob/master/docker-compose.yml#L30

#### Series
Midarr - https://github.com/midarrlabs/midarr-server/blob/master/docker-compose.yml#L11
Sonarr - https://github.com/midarrlabs/midarr-server/blob/master/docker-compose.yml#L44

I've been able to replicate this and it's not subtitle related as I first thought. 

It comes down to your mount paths for Midarr. Please reference the `docker-compose.yml` linked above and ensure Midarr mount paths (inside the container / right-hand side) are the **same** as Radarr / Sonarr paths (inside the container / right-hand side).

**Comment by parer55** [comment]
Ok, that did it,thanks. Like a stupid person I left the « path/to/sonar » like it was. It now works on my android phone and I guess it works as well on pc. On the other hand, on my iPad, it launches the player but the video never starts. Any ideas?

**Comment by lukebrandt** [comment]
After I changed the paths to what I had for Sonarr and Radarr, then it worked, thanks!

**Comment by trueChazza** [comment]
> Ok, that did it,thanks. Like a stupid person I left the « path/to/sonar » like it was. It now works on my android phone and I guess it works as well on pc. On the other hand, on my iPad, it launches the player but the video never starts. Any ideas?

Glad to hear it now works. After re-reading the README it could do with some further improvements to make it abit more clearer about mount paths. I'll sort that out 😄

**Comment by trueChazza** [comment]
> Ok, that did it,thanks. Like a stupid person I left the « path/to/sonar » like it was. It now works on my android phone and I guess it works as well on pc. On the other hand, on my iPad, it launches the player but the video never starts. Any ideas?

In regards to not playing on your iPad this could be iOS related and will need further digging.

I've created an issue for this - #254 If you don't mind adding any info you think could be helpful to further diagnose.
