### ISSUE TITLE
Add back ability to use postgresql

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#252]
Hi 👋🏼 

One thing I liked about this project was being able to scale midarr to n number of containers in Kubernetes, now with sqlite being the only option that is impossible. Please bring back postgres as a option to use for the database.

Thanks!

**Comment by aleksasiriski** [comment]
+1 for this, even Radarr/Prowlarr/Lidarr/Readarr added Postgres recently

**Comment by trueChazza** [comment]
Thanks for opening this issue. Yes having postgres as an option would be ideal.

I've tagged this for the next release `v2.1.0`. I'll keep you updated 😄

**Comment by trueChazza** [comment]
How would we feel about reverting back to postgres instead? Not ideal but I'm failing to think of a reason to keep sqlite support at all. It's been nothing but problematic from the start.

Thoughts?

**Comment by onedr0p** [comment]
Do it!

**Comment by trueChazza** [comment]
Will move this to ‘v3.0.0’ as breaking change.

**Comment by trueChazza** [comment]
Hi everyone,

`v3.0.0-beta.2` contains postgres support. README has been updated also - https://github.com/midarrlabs/midarr-server/tree/v3.0.0-beta.2#docker-compose

**Comment by trueChazza** [comment]
There won't be any breaking changes with the database schema etc from here on. Feel free to run `v3.0.0-beta.2` til the major release.
