### ISSUE TITLE
Investigate iOS playback

### ISSUE THREAD

**Issue by trueChazza** [midarrlabs/midarr-server#254]
Media not playing on iOS.

Please provide the following info to assist this:

- iOS version
- Media info (container, video codec, audio codec)
- Browser
- Browser version

Thank you!

**Comment by parer55** [comment]
IOS version : 15.0.1.
Model : IPad 2021.
Media info : any media, h264 or h265, all mkv.
Browser : tested on latest Safari and brave.

**Comment by parer55** [comment]
![IMG_20230116_090326_651](https://user-images.githubusercontent.com/4091964/212627464-30cd9cca-0700-4871-93d7-6d9ae56ae79b.jpg)

**Comment by parer55** [comment]
https://pastebin.com/NwhC0Ekq

**Comment by trueChazza** [comment]
Awesome thank you! I’ll look into this and get back to you asap

**Comment by trueChazza** [comment]
Thank you for your patience with this one. After some testing it seems iOS doesn't support **mkv**
**mp4** play just fine.

**Comment by trueChazza** [comment]
> https://pastebin.com/NwhC0Ekq

Logs look fine. It's the client (iOS) in this case that doesn't support the container (mkv)

**Comment by parer55** [comment]
Oh. So no way to enable it in the futur? At all? Such a shame... ☹

**Comment by trueChazza** [comment]
I do have an issue #210 to look into audio transcoding at the server level for next release. Maybe while I'm there I could also look into what it will take to remux or encode **mkv** to **mp4** on the fly too?

That way you can set what the output container and audio will be from your sever settings.

**Comment by trueChazza** [comment]
#258

Tagged for next release `v2.1.0` I'll keep you updated 😄

**Comment by trueChazza** [comment]
Hi @parer55 
I'm happy to announce this is now in `v2.1.0-beta.6`

You'll find a new "Test" button, next to the "Play" button for your media.
Any feedback is appreciated 😄 thanks.

**Comment by parer55** [comment]
Hello,
Thanks for the new beta version. Doesn't seem to do the trick however. Below a paste of my logs. Ask if you want me to give you anything else. 
---
[https://pastebin.com/r9RL0gTD](https://pastebin.com/r9RL0gTD)

**Comment by parer55** [comment]
This is what happens after a few seconds of loading. 
![743CC435-13B8-41FA-A0CB-D68FF3306137](https://user-images.githubusercontent.com/4091964/220567815-ca75f446-0207-46d8-81fc-82eb67c6e4fe.jpeg)

**Comment by parer55** [comment]
Ok now i've managed to get sound on this file for a few minutes : 
[https://pastebin.com/t2GrusZZ](https://pastebin.com/t2GrusZZ)

**Comment by trueChazza** [comment]
Awesome thank you for sending this through. I’ll look into it further and get back you.

**Comment by parer55** [comment]
If you need anything, knock on my door!

**Comment by trueChazza** [comment]
I’ve tracked down the issue. Aiming to have a fix up over the next few days. Thanks for testing this out!

**Comment by trueChazza** [comment]
This is exciting by the way! Up until now Midarr has only served media as is.

Remuxing on the fly opens up alot of new possibilities like on demand transcoding for example.

Super exciting, so thank you again for bringing this up and helping push this forward!

**Comment by trueChazza** [comment]
`v2.1.0-beta.7`

Give this build a go 😄

**Comment by trueChazza** [comment]
> Ok now i've managed to get sound on this file for a few minutes : https://pastebin.com/t2GrusZZ

This is a 4K video too, which I'm not sure if iOS Safari supports. Remember this update is only allowing the container i.e. mkv, to be remuxed on the fly to a wider supported container i.e. mpeg-ts, for playback.

Could you also try a 1080p video?

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/discussions/292

@parer55 special thanks for helping with this release.
