### ISSUE TITLE
is this webbase ? 

### ISSUE THREAD

**Issue by aniel300** [midarrlabs/midarr-server#263]
not sure were to post this but is this web base and is there nay plan so create, android, ios, etc apps?

**Comment by trueChazza** [comment]
Hi there, thank you for posting this issue.

Yes, the frontend for the core / server part of Midarr is web based. Mobile apps are not currently on the roadmap / project board, but are definitely possible.

Is there a particular feature or functionality of a native mobile app you're looking for - that can't be found or achieved in the current web based client?

**Comment by aniel300** [comment]
well 99 percent of pp consume their content on those mentioned platforms, as for features i would like to see live tv and music support aside from movies and tv shows.

**Comment by trueChazza** [comment]
Midarr is beautifully suited for mobile screens. You can consume your content on large and small screens with the web client.

Feel free to open any issues you come across, I’m more than happy to help.

**Comment by trueChazza** [comment]
In regards to live tv and music support, Midarr does take a unique approach and aims to extend the already existing services within your media stack.

With that said, support for those is entirely possible and could be supported in the future. Click “Watch on the repo for future updates 😄

**Comment by aniel300** [comment]
ok thank u very much, keep up the good work
