### ISSUE TITLE
'Internal Server Error' when playing a file

### ISSUE THREAD

**Issue by lborruto** [midarrlabs/midarr-server#268]
Hello there,
I got `Internal Server Error` whenever I try to play a movie or a tv show using rClone and MergerFS (everything works fine with Plex or Jellyfin).

My media paths:
`/data/mount_mergerfs/gdrive/media/movies:/radarr/movies/path`
`/data/mount_mergerfs/gdrive/media/tv:/sonarr/shows/path`

Path on Radarr: 
![Screenshot_1](https://user-images.githubusercontent.com/33548688/215585889-dafc012e-24b9-4837-9636-042dbc933759.png)

And my logs : 

> 20:15:45.293 request_id=Fz8vcC_xrcmMYnUAAAAC [info] GET /movies/210/watch
20:15:45.445 request_id=Fz8vcC_xrcmMYnUAAAAC [info] Sent 500 in 152ms
20:15:45.448 [error] #PID<0.600.0> running MediaServerWeb.Endpoint (connection #PID<0.599.0>, stream id 1) terminated
Server: XX.XX.XX.XX:4000 (http)
Request: GET /movies/210/watch
** (exit) an exception was raised:
    ** (File.Error) could not list directory "/data/mount_mergerfs/gdrive/media/movies/10 Cloverfield Lane (2016)": no such file or directory
        (elixir 1.13.4) lib/file.ex:1590: File.ls!/1
        (media_server 2.0.0) lib/media_server/subtitles.ex:15: MediaServer.Subtitles.get_subtitle/2
        (media_server 2.0.0) lib/media_server/subtitles.ex:22: MediaServer.Subtitles.has_subtitle/2
        (media_server 2.0.0) lib/media_server_web/live/watch_movie_live/show.html.heex:18: anonymous fn/2 in MediaServerWeb.WatchMovieLive.Show.render/1
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7

Thanks for any answer!

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/issues/251#issuecomment-1382904367

Hi, thanks for opening this issue. Sorry for the confusion, does the link provided help?

**Comment by lborruto** [comment]
> [#251 (comment)](https://github.com/midarrlabs/midarr-server/issues/251#issuecomment-1382904367)
> 
> Hi, thanks for opening this issue. Sorry for the confusion, does the link provided help?

Ok it's working now! It's a bit weird, since my path in sonarr/radarr containers are just `/data`, so on Midarr I just mounted once `/data:/data` and it worked! No need to get 2 volume mounted for tv shows AND movies.

**Comment by trueChazza** [comment]
Thanks for reporting back.

In terms of TV Shows posters not showing up, this is a known issue also.
Are you using an ad blocker? Try disabling or whitelisting the artworks / posters domain `https://artworks.thetvdb.com`

**Comment by trueChazza** [comment]
The permanent solution for this would be to proxy the artwork requests through Midarr, and have it return the posters instead.

There is an issue to address this in a future version:
https://github.com/orgs/midarrlabs/projects/1/views/1?filterQuery=res&pane=issue&itemId=8299600

**Comment by GregTroar** [comment]
I am having the same issue and I do not understand the behavior of Midarr on this.
My setup is that Radarr and Sonarr are NOT on docker but rather installed on a remote Linux server.

Thus I mounted a folder for MIdarr to be able to see the media and this is how my docker compose file is for volumes:

      - /mnt/Multimedia/Movies:/radarr/movies
      - /mnt/Multimedia/Series:/sonarr/shows

when I try to read a movie I get this error:

Request: GET /movies/708/watch
** (exit) an exception was raised:
    ** (File.Error) could not list directory "/mnt/Multimedia/Movies/*****": no such file or directory
        (elixir 1.13.4) lib/file.ex:1590: File.ls!/1

What I do not understand is why Midarr docker container is actually not looking for the file in /radarr/movies but rather is looking on the host folder ?
The point of volumes is to mount the local data to the docker container in order for the container to actually have access inside the docker container.

So actually to solve my issue I have to change the volumes as per below:

      - /mnt/Multimedia/Movies:/mnt/Multimedia/Movies
      - /mnt/Multimedia/Series:/mnt/Multimedia/Series

That is to say:

- some/path:/some/path
- some/other/path:/some/other/path

I think it should be stated more clearly in the wiki.

Thanks

**Comment by trueChazza** [comment]
Hi @GregTroar thank you for your feedback.

Sorry this has been quite a confusing topic. Just to clarify, Midarr uses the paths returned from the Radarr and Sonarr APIs for resolving your media locations - hence why volumes mounted into Midarr, must match the same paths mounted into Radarr and Sonarr.

I think this has caused enough confusion to warrant a better approach. I will tag this as a bug for me to fix in the next release and if you're happy to - I will run the approach past us in this thread to make sure it makes sense 😄

**Comment by trueChazza** [comment]
Again, thanks everyone for your feedback - it really helps continual improvement.

**Comment by trueChazza** [comment]
This is looking to be a breaking change:

#### Proposed
`/path/to/movies:/movies`
`/path/to/shows:/shows`

#### Previous
`/path/to/movies:/radarr/movies/path`
`/path/to/shows:/sonarr/shows/path`

**Comment by trueChazza** [comment]
Any objections or comments on this approach?

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/pull/277/files#diff-891b2c88128e996e97b2801f537c8e4f2f6798f7b6eb3cd6abc5a239838a1613

Reference

**Comment by GregTroar** [comment]
Awesome

**Comment by trueChazza** [comment]
> > [#251 (comment)](https://github.com/midarrlabs/midarr-server/issues/251#issuecomment-1382904367)
> > Hi, thanks for opening this issue. Sorry for the confusion, does the link provided help?
> 
> Ok it's working now! It's a bit weird, since my path in sonarr/radarr containers are just `/data`, so on Midarr I just mounted once `/data:/data` and it worked! No need to get 2 volume mounted for tv shows AND movies.
> 
> Still have a weird issue where TV Shows poster are not showing up...

Hi @lborruto

If you're willing to try an early beta release - `ghcr.io/midarrlabs/midarr-server:v3.0.0-beta.1` contains a fix for the TV Shows posters not showing up.
