### ISSUE TITLE
Internal Server Error when logging in

### ISSUE THREAD

**Issue by theAlevan** [midarrlabs/midarr-server#273]
When I log in on the Web UI, I get the **Internal Server Error** message. I use a Fedora 37 based Docker Swarm.

This is the log about the event:
`[error] #PID<0.589.0> running MediaServerWeb.Endpoint (connection #PID<0.581.0>, stream id 5) terminated`
`Server: 10.0.2.1:4050 (http)`
`Request: GET /`
`** (exit) an exception was raised:`
`    ** (BadMapError) expected a map, got: nil`
`        (stdlib 3.17.2.1) :maps.find("images", nil)`
`        (media_server 2.0.0) lib/media_server/helpers.ex:40: MediaServer.Helpers.get_background/1`
`        (media_server 2.0.0) lib/media_server_web/live/home_live/index.html.heex:7: anonymous fn/2 in` `MediaServerWeb.HomeLive.Index.render/1`
`        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7`
`        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7`
`        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3`
`        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7`
`        (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7`

**Comment by trueChazza** [comment]
Hi thank you for opening this issue.

This is happening due to your latest movie from Radarr not having any images, or no movies at all.

**Comment by trueChazza** [comment]
I’ll tag this as a bug for me to follow up on, as ideally it shouldn’t error.

**Comment by trueChazza** [comment]
This will be fixed in next release - `v2.1.0`

Thanks for reporting!
