### ISSUE TITLE
OIDC support 

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#309]
Hi 👋

It would be great if midarr supported OIDC so that I could use something like Authelia or Authentik to provide access to my existing managed friends and family.

**Comment by trueChazza** [comment]
Hi @onedr0p that sounds awesome! I've tagged this for the next minor release `v3.1.0`
I'll be in touch then - thanks!

**Comment by onedr0p** [comment]
I would mainly ask if these options could be configurable via env vars rather than in the UI. Thanks!

**Comment by trueChazza** [comment]
Sounds good! I'll let you know when I've started working on this 😄

**Comment by onedr0p** [comment]
@trueChazza it might help understanding what env variables could be used to help drive the code. I was thinking these might be a good start. 

```
OAUTH_ENABLED: "true"
OAUTH_ISSUER_URL: https://auth.domain.com/.well-known/openid-configuration
OAUTH_CLIENT_ID: "midarr"
OAUTH_CLIENT_SECRET: "some-random-text-string"
OAUTH_AUTO_REGISTER: "true"
OAUTH_BUTTON_TEXT: "Login with Authelia"
```

**Comment by trueChazza** [comment]
Awesome, thanks for sending this through. This gives me a good base to start with 👍

**Comment by trueChazza** [comment]
All good if I move this into release `v3.2.0`?

**Comment by trueChazza** [comment]
> @trueChazza it might help understanding what env variables could be used to help drive the code. I was thinking these might be a good start.
> 
> ```
> OAUTH_ENABLED: "true"
> OAUTH_ISSUER_URL: https://auth.domain.com/.well-known/openid-configuration
> OAUTH_CLIENT_ID: "midarr"
> OAUTH_CLIENT_SECRET: "some-random-text-string"
> OAUTH_AUTO_REGISTER: "true"
> OAUTH_BUTTON_TEXT: "Login with Authelia"
> ```

@onedr0p Would you be keen to add the oauth button to the login page as you've described above?
So maybe show button when `OAUTH_ENABLED: "true"` and button text with `OAUTH_BUTTON_TEXT: "Login with Authelia"`

**Comment by trueChazza** [comment]
@onedr0p Once I've merged #374 you could work off master for the oauth button.

**Comment by onedr0p** [comment]
I'll give it a shot when I have time 👍🏼

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server#local-development

You should be able to just docker-compose up
