### ISSUE TITLE
Support Sonarr v4 API

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#315]
These versions are the current `develop` branch. It's annoying these apps how so many different channels to deal with but I've been running Sonarr and Radarr on `develop` / v4 for a very long time and it's been very stable. It might make sense to start expecting a v4 release of Sonarr this year sometime.

**Comment by onedr0p** [comment]
It is worth nothing that there doesn't seem to be anything broken I can see using v4 of Radarr and Sonarr currently with Midarr. However many not picking up TV thumbnails is related?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/213795/226751804-42d385d7-ce3e-463f-908b-d518a0028302.png">

**Comment by onedr0p** [comment]
It doesn't look like Midarr it returning the whole library in the Movies or Series view. Only 50 items are returning.

**Comment by onedr0p** [comment]
It looks like Radarr and Sonarr v4 both use their v3 APIs. There is nothing to do here.

**Comment by trueChazza** [comment]
https://github.com/orgs/midarrlabs/projects/1/views/1?filterQuery=sonarr+v4

No you're right, I even have a backlog issue to add support for Sonarr V4 as you've mentioned. The API itself is still versioned v3 for both Sonarr V3 and V4 - however I have looked into it and there are slight changes.

Same v3 versioned API, but it has breaking changes - episode thumbnail / screenshot schema included. Kind of mind blowing they've left the version the same.

Reopening 😄 thanks again!

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/actions/runs/4496942700/jobs/7912075291

Just for fun, pointed CI at Sonarr V4 and it fails quite early on in the build. Looking forward to getting this building soon though.

**Comment by trueChazza** [comment]
I'll look into this when Sonarr V4 stable is released. Supporting a develop branch could cause all sorts of issues for us.

**Comment by trueChazza** [comment]
Thinking I'll just pull the pin on this based on the amount of feedback I've been receiving.

It will be a breaking change so `v5.0.0`

**Comment by trueChazza** [comment]
I'll confirm here when in a build
