### ISSUE TITLE
RFC: Integrate optional search service to speed up searching

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#316]
Having a large libraries searching can be quite slow, there are applications like [typesense](https://typesense.org/) that could be ran alongside midarr and if integrated can help speed up searching quite a bit. I tried finding a tool like that with an elixir SDK but nothing turned up.

I am just curious on if this could be viable or if there are any other ways to help speed up searching.

**Comment by trueChazza** [comment]
https://github.com/orgs/midarrlabs/projects/1/views/1?filterQuery=search+agent

Thanks for this. There are a couple issues in the backlog for me to investigate this further.
Yes currently, Midarr uses Radarr / Sonarr APIs to search. The issues linked were to search the caching mechanism instead, which should 🤞 hopefully speed this up.

**Comment by trueChazza** [comment]
> For typesense, there is an Elixir client lib at https://github.com/jaeyson/ex_typesense. There's also https://github.com/heywhy/ex_elasticlunr if you wanted to keep the search entirely inside Elixir.

Thanks for that, the JSON search looks interesting. I'll take a look through when I'm up to here 😄

**Comment by trueChazza** [comment]
`v3.1.0-beta.2`

First pass on improving search. This now uses the caching mechanism 😄

**Comment by trueChazza** [comment]
@onedr0p Let me know how it goes on your large library. It's improved significantly on my library.

**Comment by onedr0p** [comment]
Wow searching it much faster and more accurate!

**Comment by trueChazza** [comment]
https://github.com/orgs/midarrlabs/projects/1/views/1?filterQuery=search

Cool thanks for the feedback. I've added a couple more issues to further improve search later.
