### ISSUE TITLE
Reduce the size of the docker image

### ISSUE THREAD

**Issue by onedr0p** [midarrlabs/midarr-server#317]
The current size of the docker image is pretty large at `1.62GB` I am not familiar enough with elixir but maybe there are some optimizations to be had to help reduce the size? The elixir base image used being `552MB` doesn't really help much, can you perhaps use the `-slim` or `-alpine` variant?

https://hub.docker.com/layers/library/elixir/1.14.3-otp-24-slim/images/sha256-45979073f4854e367c5f6406d542e1503dc926bbf9f35102afcc5b06b1bcc748?context=explore

https://hub.docker.com/layers/library/elixir/1.14.3-otp-24-alpine/images/sha256-11162baec6c2aab11df01abbeb3fd0de07b251becd53363782c623162be11483?context=explore

Another thing that I noticed is that you're copying in all of the repo `COPY . ./` into `/app`. It might be a good idea to use a `.dockerignore` file in the root of the repo so only required things are copied in.

**Comment by onedr0p** [comment]
Omitting the `dev` and `docs` directory would save ~350MB

```bash
❯ du -sh *
68K	assets
4.0K	code-coverage.sh
8.0K	CODE_OF_CONDUCT.md
20K	config
4.0K	coveralls.json
321M	dev
4.0K	docker-compose.yml
4.0K	Dockerfile
22M	docs
4.0K	entry-local.sh
4.0K	entry.sh
420K	lib
4.0K	LICENSE
4.0K	mix.exs
20K	mix.lock
204K	priv
8.0K	README.md
168K	test
```

**Comment by onedr0p** [comment]
With excluding the `dev` and `docs` this Dockerfile brings the image down to ~700MB total.

```Dockerfile
FROM node:18-alpine as node

WORKDIR /assets

COPY assets/package.json assets/package-lock.json /assets/
RUN npm install

#-------------------------

FROM elixir:1.14.3-otp-24-alpine

ARG MIX_ENV="dev"
ARG SECRET_KEY_BASE=""

ENV MIX_ENV="${MIX_ENV}"
ENV SECRET_KEY_BASE="${SECRET_KEY_BASE}"

RUN MIX_ENV=$MIX_ENV
RUN SECRET_KEY_BASE=$SECRET_KEY_BASE

WORKDIR /app

COPY . ./
COPY --from=node /assets/node_modules /app/assets/node_modules/

RUN \
    apk add --no-cache --virtual=.build-deps \
        build-base \
    && \
    apk add --no-cache \
        ca-certificates \
        ffmpeg \
        inotify-tools \
        postgresql15-client \
    && \
    mix local.hex --force \
        && mix local.rebar --force \
        && mix deps.get \
        && mix deps.compile \
        && mix assets.deploy \
        && mix compile \
    && apk del --purge .build-deps \
    && rm -rf /tmp/* \
    && chmod u+x /app/entry.sh

EXPOSE 4000

CMD [ "/app/entry.sh" ]
```

**Comment by trueChazza** [comment]
This is so awesome wow thank you!

You're 99% the way there with this already - a PR would be amazing to finish it 😃

The [test workflow](https://github.com/midarrlabs/midarr-server/blob/feature/v3.0.0/.github/workflows/test.yml) runs the build / tests for all branches on push. If you branched off of the `feature/v3.0.0` branch and opened a PR with your Dockerfile changes, you'd be able to see if the build passes or not in GitHub, without you even touching any of the Elixir stuff 😄

Plus of course I'll help you getting it merged in! Looking forward to your PR - so cool!

**Comment by onedr0p** [comment]
Sure I can try. Do you know which files or folders in the root of the repo should be ignored from being cooped into the container?

**Comment by trueChazza** [comment]
Definitely `/dev` and `/docs` as you've mentioned. 

With the alpine image as well, this is a huge improvement to start - we can improve it over time.

**Comment by trueChazza** [comment]
I'll tag a new beta build for us to test out too.

**Comment by onedr0p** [comment]
Sounds good, I'll give it a try 🙂

**Comment by trueChazza** [comment]
`v3.0.0-beta.6`

Thanks for your work on this!
