### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by jaafar-c** [midarrlabs/midarr-server#398]
Hello,
I get the wrong password or email message even though I tripled checked my email and password specified in the config.
please help

**Comment by trueChazza** [comment]
Hi! What have you tried? Is your password a minimum length of 12 characters?

**Comment by jaafar-c** [comment]
I downloaded docker-compose.yml then changed the email and password you mentioned. The password is '1234567890jj' so it's 12 character in length.

**Comment by trueChazza** [comment]
Interesting - I tried `admin2@email.com` and `1234567890jj ` and I was able to login successfully.

**Comment by trueChazza** [comment]
If you could post any log errors for me to assist further, that would be helpful
