### ISSUE TITLE
[BUG]: Media Sync API key

### ISSUE THREAD

**Issue by lukebrandt** [midarrlabs/midarr-server#410]
**Describe the bug**
Trying to set up media syncing and don't know what the some-api-token is.  I've tried the Sonarr or Radarr API key, but it returns a HTTP request failed, which makes sense because I would assume it would be looking for a Midarr API key.

**To Reproduce**
1. Create webhook in Sonarr or Radarr
2. Copy webhook URL into the URL of the webhook setup.
3. Don't know what to put in for the some-api-token.

**Expected behavior**
I would expect something in the Midarr web interface or the docker logs displaying my API key, or documentation pointing me to where I can find it.  If it is available and I didn't find it, I apologize, but I did a search through the repo

**Desktop (please complete the following information):**
 - OS: Running it in docker on Synology
 - Browser: Edge
 - Midarr Version 4.10

**Comment by trueChazza** [comment]
`ghcr.io/midarrlabs/midarr-server:v4.1.2`

Hi, thank you for opening this issue. Yes sorry about that, you're correct. There was no display of the api token in Midarr itself. The only way to access it was through the database.

I've pushed a new release that adds an API Token field to the Settings page. Please use the new image above 😄

**Comment by lukebrandt** [comment]
Great, thanks! I did pull the new image and recreated the container.  I did get an Internal Server error the first time, but destroyed the container and recreated it and then I was able to login and view the API field in the settings.

The field in the settings is editable.  If you change the key, does that actually change the API key, or will editing it screw something up?

**Comment by trueChazza** [comment]
No worries! The field is editable but any changes to the api token won’t persist.

I’ll make some improvements over the next few releases so it’s not editable as well.
