### ISSUE TITLE
API oversight for seasonCount

### ISSUE THREAD

**Issue by mintexists** [midarrlabs/midarr-server#510]
**Is your feature request related to a problem? Please describe.**
I am setting up a TUI client for Midarr, and it seems to me an oversight that `/api/series` does not include `seasonCount` for each series, but otherwise contains all the same information as `/api/series/:id`. 

**Describe the solution you'd like**
Include `seasonCount` as part of the items returned by the `/api/series` endpoint.

**Describe alternatives you've considered**
Currently you can just send an additional api request to `/api/series/:id`, but because this is the only difference that the two return, that is a lot of redundancy.

**Additional context**
I really enjoy how minimalistic Midarr is!

**Comment by trueChazza** [comment]
Hi thank you for opening the issue, and glad to hear you're enjoying Midarr 😀

Definitely an oversight on my part for not adding `seasonCount` to the `:id` endpoint.

If you don't mind me asking which Midarr version are you using?

**Comment by mintexists** [comment]
I am using v4.2.0 which is the :latest docker tag

**Comment by trueChazza** [comment]
Awesome thank you!

I've added this to `v4.3.0` release. I'll let you know when there's a build ready 👍

**Comment by trueChazza** [comment]
* Build - https://github.com/midarrlabs/midarr-server/pkgs/container/midarr-server/258808936?tag=v4.3.0
* Release notes - https://github.com/midarrlabs/midarr-server/releases/tag/v4.3.0

Done! Thanks again for opening issue, feel free to open any further issues.
