### ISSUE TITLE
Add Chromecast support

### ISSUE THREAD

**Issue by midarrlabs** [midarrlabs/midarr-server#67]

**Comment by Erwyn** [comment]
Hi,

I've seen your pull request regarding this but haven't found in the interface how to play something on the chromecast. Is it already there, or is there still a missing piece to this ?

Thanks !

**Comment by trueChazza** [comment]
Hi there, may I ask which client interface you're referring to i.e. Android, iOS?

**Comment by Erwyn** [comment]
Oh, my bad, I actually only used the web interface and expected to find a button there. If I understand, you're suggesting me to use a dedicated client instead ?

**Comment by trueChazza** [comment]
You can cast from a browser using the browsers' own interface, for example Google Chrome:

https://support.google.com/chromecast/answer/3228332?hl=en&co=GENIE.Platform%3DDesktop

**Comment by trueChazza** [comment]
#141

I've created an issue to add a Chromecast button to the app interface. Feel free to subscribe for updates on the issue.

**Comment by Erwyn** [comment]
Thanks for the pointer. So just to be sure, there is no Android or IOs client right ? One is supposed to access directly the web frontend from the mobile.

**Comment by trueChazza** [comment]
Yes that is correct. No native Android or iOS clients. Only browser based (mobile and desktop) access for now.

**Comment by Erwyn** [comment]
Super, thank you very much for your answers !
